# Generated by Django 5.2.9 on 2025-12-12 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'Mastercard'), ('RUPAY', 'RuPay'), ('AMEX', 'American Express'), ('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
